### ISSUE TITLE
Steering Committee Nominations - Nov 2019

### ISSUE THREAD

**Issue by julianpistorius** [resbazaz/core_mission#3]
### Nominations are open for the Research Bazaar Arizona Steering Committee

This is the first iteration of a new process to involve more of our community members in the day-to-day decision making and organizing of ResBazAZ activities.

From the HackMD document below:

- We assume that we are going to need an executive/steering committee
- The first (zero-th) iteration of the above process will be to find dedicated volunteers for the executive committee
- This group will help oversee and organize the next iteration of the process
- They will also help refine and codify the process described here
- We should formalize this group as soon as possible!

The role of steering committee member should have a defined and limited responsibility, with a known time commitment. It's a crucial role, but it should not take up a lot of a busy person's time.

Please feel free to nominate yourself or somebody else in the ResBazAZ community. Suitable candidates will be members who are active and in good standing.

This will be a short term (a few months at most) while we figure out the processes for the longer term.

### To nominate someone

- Add a comment below this issue with the GitHub username of the person you want to nominate
- You can nominate yourself
- If you want to nominate multiple people, please use separate comments for each nominee
- Nominations will close on Monday, 18 November, 11am MST

### Voting

- Voting will be done by the members of the [interim executive team](https://github.com/orgs/resbazaz/teams/executive/members) by giving a 'thumbsup' emoji (👍) on each nomination
- Each members of the [interim executive team](https://github.com/orgs/resbazaz/teams/executive/members) will get three votes.
- Voting will open on Monday, 18 November, 11am MST
- Voting will close on Tuesday, 19 November, 11am MST

**Note:**

- For this first iteration the steering committee will be capped at nine (9) members
- A minimum of five (5) members must currently be on the [interim executive team](https://github.com/orgs/resbazaz/teams/executive/members)
- The remaining four (4) can be from outside the [interim executive team](https://github.com/orgs/resbazaz/teams/executive/members)

### Bowing out

If a person is nominated, but is unable to serve in this term, then they can add a 'thumbs-down' emoji (👎) on the nomination comment that mentions them.

### Ratification

New steering committee members will be ratified by quorum at the [monthly executive meeting](https://www.meetup.com/ResBazAZ/events/bfhgqnyzpbzb/) to be held on Tuesday, 19 November, noon MST at Bentley's

### Background

- https://hackmd.io/fdRXEcqSQEGt7oOmMUy_Iw
- https://github.com/carpentries/executive-council-info

**Comment by megbalk** [comment]
Emily Cain

**Comment by megbalk** [comment]
Ailene

**Comment by megbalk** [comment]
@drakeasberry

**Comment by megbalk** [comment]
@vanderpoolrr

**Comment by jberghout** [comment]
@megbalk

**Comment by megbalk** [comment]
@alex-r-bigelow

**Comment by megbalk** [comment]
Boris

**Comment by yeea** [comment]
@bjoyce3

**Comment by yeea** [comment]
@julianpistorius

**Comment by bjoyce3** [comment]
@yeea

**Comment by drakeasberry** [comment]
@kelseygonzalez

**Comment by julianpistorius** [comment]
@jennytnichols

**Comment by julianpistorius** [comment]
@jcoliver

**Comment by julianpistorius** [comment]
@jberghout

**Comment by MagicMilly** [comment]
If you start your comment with `:` this will pop up 👍

**Comment by jcoliver** [comment]
But we are supposed to :+1: individual comments as a voting mechanism...

**Comment by kelseygonzalez** [comment]
Perhaps @julianpistorius can clarify the voting procedure and how we use the 👍  in this format?

**Comment by julianpistorius** [comment]
Thank you everybody! And congratulations.
