### ISSUE TITLE
Update website with names & profiles of steering committee members

### ISSUE THREAD

**Issue by julianpistorius** [resbazaz/core_mission#6]
Hi steering committee members. 

Please add a photo & profile (240 characters) (Hogwarts House optional) as a comment to this issue:

- [x] Emily - @MagicMilly
- [x] Ailene - @yeea 
- [x] Drake - @drakeasberry 
- [x] Rebecca - @vanderpoolrr 
- [x] Alex B. - @alex-r-bigelow
- [x] Blake - @bjoyce3 
- [x] Julian - @julianpistorius 
- [x] Kelsey - @kelseygonzalez 
- [x] Jeff - @jcoliver

**Comment by jcoliver** [comment]
As the UA Libraries Data Science Specialist, I agitate and advocate for campus data and computational literacy. I work mostly in R and retain a modicum of phylogenetics theory. As a graduate student, I chased butterflies and learned Java.
![Jeff Oliver 2019 Portrait_1](https://user-images.githubusercontent.com/1939813/69363070-f83cbf80-0c4c-11ea-8f4f-64b2e967275c.jpg)

**Comment by jcoliver** [comment]
OMG, that's giant photo.

**Comment by alex-r-bigelow** [comment]
I'm a postdoc from Computer Science, studying how people think about, reshape, and visualize data. I build web-based tools to make these processes less painful, and more accessible to more diverse data workers. Slytherin.

![IMG_20180617_084133](https://user-images.githubusercontent.com/1215873/69372752-9174d180-0c5f-11ea-8828-0ef06e9f2136.jpg)

**Comment by drakeasberry** [comment]
I am a PhD Candidate in Second Language Acquisition and Teaching (SLAT). You can find me at Public, the University, climbing big rocks, or in the Slytherin Common Room. 
![image](https://user-images.githubusercontent.com/47766074/69386490-0821c700-0c80-11ea-898f-68646b582863.png)

**Comment by kelseygonzalez** [comment]
As a PhD student in Sociology, I am an advocate for data science literacy and love experimenting with R.  Besides learning new methodologies, I enjoy baking pizza and hiking on Mt Lemmon with my dog. 
![Kelsey-Gonzalez](https://user-images.githubusercontent.com/50840312/69397928-4ed5e800-0ca5-11ea-8f35-18620735a944.jpg)

**Comment by MagicMilly** [comment]
I work as a scientific programmer for the Agricultural Data Science Team. My hobbies include contemplating the ways in which open data and open science can change the world, trying to guess people's Hogwarts House (Slytherin), and my cat.
![Cain_pic](https://user-images.githubusercontent.com/34486154/69447461-cc384180-0d13-11ea-8a4e-0a86e7407719.jpg)

**Comment by yeea** [comment]
I’m a software engineer with CyVerse who also studies the ancient Greco-Roman world. Making things accessible to others, reading, biking, eating and eating more, languages, and video games are my bread and butter.
![IMG_20190929_210817](https://user-images.githubusercontent.com/560767/69508612-8c2fb500-0ef3-11ea-8623-3e1ea45968a2.jpg)

**Comment by vanderpoolrr** [comment]
I am an Assistant Professor in the College of Medicine. My research focuses on using CMR imaging and cardiopulmonary exercise testing to assess the pathophysiology of right ventricular function and to develop clinically useful biomarkers. 

![201804698-vanderpool-rebecca-659](https://user-images.githubusercontent.com/41706915/69594142-a5e70000-0fb8-11ea-9f1e-46e2f9621275.jpg)

**Comment by julianpistorius** [comment]
I build software and infrastructure for researchers. I create software for fun. I like to talk about software. I don't understand what "work-life balance" means. I _do_ like to ride motorcycles and go hiking. Gryffindor.

![julian-pistorius-2019-11-cropped](https://user-images.githubusercontent.com/742633/70285926-1cf27480-17c1-11ea-9f86-f1f957c92df2.jpg)
